### ISSUE TITLE
libRNDigits.a path

### ISSUE THREAD

**Issue by arhmnsh** [fixt/react-native-digits#2]
Hi!
Third step from the Setup iOS section:
3. Add libRNDigits.a to Build Phases -> Link Binary With Libraries

Where is this `libRNDigits.a` file?

**Comment by madwed** [comment]
If you click on the `+` next to `Build Phases` you will see it in the menu that pops up.

**Comment by pgarciacamou** [comment]
> If you click on the + next to Build Phases you will see it in the menu that pops up.

@madwed I'm unable to find `libRNDigits.a` file as well. Could you add a screenshot of _"click on the + next to Build Phases"_?

**Comment by pgarciacamou** [comment]
@madwed 

I unsuccessfully tried following some other tutorials to install Digits because I can't find the file (e.g. https://fabric.io/kits/ios/digits/install).

Could you provide more insight on how to get `libRNDigits.a`?

**Comment by madwed** [comment]
Click on your app from the left menu
Then click on Build Phases
Then open the reveal with the `Link Binary With Libraries` title
At the bottom of the list list of your already linked binaries is a `+` symbol
Click that and select the `libRNDigits.a` file
