### ISSUE TITLE
TwitterCore doesn't support iOS 7.x and lower. Please, change your minimum deployment target to iOS 8.0

### ISSUE THREAD

**Issue by sibelius** [fixt/react-native-digits#7]
it looks like that TwitterCore require iOS 8, so you need to change it on RNDigits.xcodeproj

**Comment by cgarvis** [comment]
Can you provide some documentation on this change and possible a PR?

**Comment by sibelius** [comment]
https://github.com/twitterdev/fabric-timelines-ios/blob/master/TimelinesObjC/TwitterCore.framework/Headers/TwitterCore.h#L24

**Comment by sibelius** [comment]
you need to edit xcodeproj and change the build to 8.0 instead of 7.0

**Comment by esauter5** [comment]
@sibelius The fix has been merged to master. It will be published to NPM shortly (v0.2.0)

**Comment by sibelius** [comment]
tks
