### ISSUE TITLE
react and react-native should be peerDependencies

### ISSUE THREAD

**Issue by sibelius** [fixt/react-native-digits#8]
without peerDep it leads to conflicts when u upgrade the react native version

**Comment by cgarvis** [comment]
peerDependencies have been deprecated in npm 3.   Are you still using npm 2?

**Comment by sibelius** [comment]
so, I guess with need to remove react and react-native from dependencies, so we can use with newer versions of react native

**Comment by cgarvis** [comment]
With the changes in npm 3, if you have react/react-native as dependencies of your project, it should install properly.  We have the dependencies set pretty loosely, so it should just work.  I have had an issue once where npm install 2 different versions.  I remedied it by delete `node_modules` and reinstalling them all.

What are you seeing exactly?

**Comment by sibelius** [comment]
it does not work well in react native, because the packager uses @provideModules to require some files, and having two versions of react and react native is a problem

**Comment by cgarvis** [comment]
And you are using NPM 3?

**Comment by sibelius** [comment]
yep

**Comment by sibelius** [comment]
try this:

create a new react native project using another version instead of the one from react-native-digits (for instance, RN28)

install react-native-digits in this package

try to run it

u gonna have a packager conflict bc of @providesModules syntax

**Comment by sibelius** [comment]
@cgarvis I've submitted a PR to address this issue, could u please review it

**Comment by esauter5** [comment]
Thanks for the help @sibelius
